// Image URL helpers. Source URLs in the data are Wikimedia Commons
// Special:FilePath links with a baked-in `width=` param. Served as-is they
// cost TWO redirect hops per image and the server snaps to sizes that don't
// match the srcset descriptors (width=320 actually serves 330px, width=1024
// serves 1280px — measured 2026-06).
//
// img-meta.json (generated by scripts/enrich-images.mjs) maps each file to
// its real upload.wikimedia.org shard path + original pixel size, so we link
// the final thumbnail URL directly: zero redirects, true descriptor widths,
// and candidates clamped below the original so nothing upscales. Wikimedia
// only renders thumbnails at fixed width buckets — anything else is HTTP 400.
// Files missing from the meta map (exotic/new) fall back to Special:FilePath.

import imgMeta from "@/data/img-meta.json";

// [origW, origH, "X/XY/Enc_Name.ext", flag?]
// flag: absent = thumb name is "{w}px-Enc_Name.ext"
//       1      = SVG: thumb name gets ".png" appended; vector, so no clamping
//       string = custom thumb-name pattern containing "{w}px-" (tif/pdf …)
type Meta = [number, number, string] | [number, number, string, 1 | string];
const META = imgMeta as unknown as Record<string, Meta>;

const UPLOAD = "https://upload.wikimedia.org/wikipedia/commons/";
// The only widths Wikimedia renders on demand (verified empirically).
const BUCKETS = [20, 40, 60, 120, 250, 330, 500, 960];

const FILEPATH_RE = /^https?:\/\/commons\.wikimedia\.org\/wiki\/Special:FilePath\/([^?]+)/;
// Some curated data links originals on upload.wikimedia.org directly (the
// ?width= param there is silently ignored — the full original is served).
const DIRECT_RE = /^https?:\/\/upload\.wikimedia\.org\/wikipedia\/commons\/.\/..\/([^/?]+)/;

function metaFor(url: string): Meta | undefined {
  const m = FILEPATH_RE.exec(url) ?? DIRECT_RE.exec(url);
  if (!m) return undefined;
  try {
    return META[decodeURIComponent(m[1]).replace(/_/g, " ").normalize("NFC")];
  } catch {
    return undefined;
  }
}

function thumbUrl(meta: Meta, w: number): string {
  const [, , path, flag] = meta;
  const encName = path.slice(path.lastIndexOf("/") + 1);
  const name =
    typeof flag === "string"
      ? flag.replace("{w}px-", `${w}px-`)
      : `${w}px-${encName}${flag === 1 ? ".png" : ""}`;
  return `${UPLOAD}thumb/${path}/${name}`;
}

// Buckets this file can actually be rendered at (rasters never upscale).
function validBuckets(meta: Meta): number[] {
  if (meta[3] === 1) return BUCKETS; // SVG: vector, any bucket is sharp
  return BUCKETS.filter((b) => b < meta[0]);
}

// Direct URL at (roughly) the requested width: the smallest renderable bucket
// >= w, else the largest one, else the original file.
export function imgAt(url: string, w: number): string {
  const meta = metaFor(url);
  if (!meta) return setWidth(url, w); // fallback: Special:FilePath redirect
  const valid = validBuckets(meta);
  const pick = valid.find((b) => b >= w) ?? valid[valid.length - 1];
  return pick == null ? UPLOAD + meta[2] : thumbUrl(meta, pick);
}

export function tiny(url: string): string {
  return imgAt(url, 20);
}

// ---- Fallback path (no meta): legacy Special:FilePath width param ----------
function setWidth(url: string, w: number): string {
  if (/[?&]width=\d+/.test(url)) return url.replace(/([?&])width=\d+/, `$1width=${w}`);
  return url + (url.includes("?") ? "&" : "?") + "width=" + w;
}

const PHOTO_WIDTHS = [360, 540, 720, 1024];
const COA_WIDTHS = [180, 240, 320, 440];

export const PHOTO_SIZES = "(min-width: 768px) 620px, 92vw";
export const COA_SIZES = "(min-width: 768px) 300px, 62vw";

// Hero srcset: renderable buckets in the useful display range, plus the
// original file itself when it's barely above the largest bucket (a sharp
// option for high-DPR screens that costs little).
function heroSrcSet(meta: Meta, minW: number): { src: string; srcSet?: string } {
  const candidates = validBuckets(meta).filter((b) => b >= minW);
  const entries = candidates.map((b) => `${thumbUrl(meta, b)} ${b}w`);
  if (meta[3] !== 1 && meta[0] > 960 && meta[0] <= 1300) {
    entries.push(`${UPLOAD}${meta[2]} ${meta[0]}w`);
  }
  if (entries.length === 0) return { src: UPLOAD + meta[2] };
  const def = candidates.find((b) => b >= 500) ?? candidates[candidates.length - 1];
  return { src: def == null ? UPLOAD + meta[2] : thumbUrl(meta, def), srcSet: entries.join(", ") };
}

export type Quality = "hd" | "lett";

// Resolve the <img> props for a prompt image given the user's quality choice.
// "lett" serves a single downsampled file (lighter + faster); "hd" serves a
// responsive srcset. Display and preload go through this so they always match.
export function heroProps(
  url: string,
  variant: "coa" | "photo",
  quality: Quality,
): { src: string; srcSet?: string; sizes?: string } {
  const meta = metaFor(url);
  if (meta) {
    if (quality === "lett") return { src: imgAt(url, variant === "coa" ? 250 : 500) };
    const minW = variant === "coa" ? 250 : 330;
    const sizes = variant === "coa" ? COA_SIZES : PHOTO_SIZES;
    const r = heroSrcSet(meta, minW);
    return r.srcSet ? { ...r, sizes } : r;
  }
  // Fallback: legacy Special:FilePath variants.
  if (variant === "coa") {
    if (quality === "lett") return { src: setWidth(url, 220) };
    return { src: setWidth(url, 320), srcSet: COA_WIDTHS.map((w) => `${setWidth(url, w)} ${w}w`).join(", "), sizes: COA_SIZES };
  }
  if (quality === "lett") return { src: setWidth(url, 480) };
  return { src: setWidth(url, 720), srcSet: PHOTO_WIDTHS.map((w) => `${setWidth(url, w)} ${w}w`).join(", "), sizes: PHOTO_SIZES };
}

// Warm the browser cache for an upcoming image, matching the displayed variant.
export function preloadImage(url: string, srcSet?: string, sizes?: string) {
  if (typeof window === "undefined") return;
  const img = new window.Image();
  if (sizes) img.sizes = sizes;
  if (srcSet) img.srcset = srcSet;
  img.src = url;
}
